---
title: "Word Embeddings Visual"
author: "Reid McIlroy-Young"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
options(shiny.sanitize.errors = FALSE)
library(ggplot2)
library(plotly)
library(plyr)
library(xkcdcolors)
library(flexdashboard)
library(shinyWidgets)

if (dir.exists('data/')) {
  filesDir <- 'data/'
} else {
  filesDir <- '/home/reid/int-reidmcy/data/'
}


target_names <- c('Economics', 'Stack Overflow', 'Psychology & Neuroscience', 'Combined')
names(target_names) <- c('Economics', 'Computer Science', 'Psychology & Neuroscience', 'Combined')

choices_names <- c('Points', 'Text', '3D')
names(choices_names) <- c('Points', 'Text', '3D')

files <- c('tsne_Economics.csv', 'tsne_Stack Overflow.csv', 'tsne_Psychology & Neuroscience.csv', 'tsne_combined.csv')
colours <- c(name2color("light orange"), name2color("light blue"), name2color("light green"), name2color("black"))

df_attributes <- data.frame(file=files, colour=colours, row.names=target_names)
#row.names(df_attributes) <- names

```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
pickerInput(inputId = 'var',
            label = 'Dataset',
            choices = target_names,
            selected ='Combined')

pickerInput(inputId = 'choice',
            label = 'Display Type',
            choices = choices_names,
            selected ='Points')


```

Column
-----------------------------------------------------------------------

### K Means
```{r}


df_target <- reactive({
  if (input$choice == '3D' ||input$choice ==  'Table 3D') {
    df <- read.csv(paste(filesDir, 'tsne_', input$var, '_3d.csv', sep = ''))
  } else {
    df <- read.csv(paste(filesDir, 'tsne_', input$var, '.csv', sep = ''))
  }
})


renderPlotly({
  if (input$choice == '3D') {
    p <- plot_ly(df_target(), x=~tsne_0, y=~tsne_1, z=~tsne_2, color = ~colour_class, size = ~size_objs * 5,
                hoverinfo = 'text', type='scatter3d',
                text = ~paste('Source: ', cName,
                  '\nTag: ', tag,
                  '\n Count: ', count,
                  '\n Rank: ', rank))
    add_markers(p)
    layout(p, showlegend = FALSE)
    p
  } else {
    tsne_plot <- ggplot(data = df_target(), aes(x=tsne_0, y=tsne_1, label=tag, size = size_objs , colour=colour_class, fill=colour_class, 
                                                 text = paste('Source: ', cName,
                                                              '\nTag: ', tag,
                                                              '\n Count: ', count,
                                                              '\n Rank: ', rank)))
  if (input$choice == 'Text') {
    tsne_plot <- tsne_plot + 
      geom_text()
  } else {
    tsne_plot <- tsne_plot +
      geom_point(colour=name2color("dark grey"), pch=21)
  }
  tsne_plot <- tsne_plot +
    labs(title = "2D t-SNE embeding") +
    theme(plot.title = element_text(size =12),
        axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank(),
        axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank(),
        panel.background=element_blank(),
        legend.position="none")
  ggplotly(tsne_plot, tooltip = c("text"))
  } 
})


```
